# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    env:
      BROWSER: ${{ matrix.browser }}
      ACTIONS_RUNNER_DEBUG: $ {{ secrets.ACTIONS_RUNNER_DEBUG }}
      ACTIONS_STEP_DEBUG: $ {{ secrets.ACTIONS_STEP_DEBUG }}
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium,firefox,webkit]
        os: [ubuntu-18.04,windows-2019,macos-10.15]
        exclude:
          - browser: webkit
            os: ubuntu-18.04
          - browser: webkit
            os: windows-2019
        os-window: [0.2.0,0.2.1,0.2.2,0.2.3]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install
      run: yarn

    - name: Peers
      run: yarn add os-window@${{ matrix.os-window }}

    - name: Lint
      run: yarn lint

    # Runs a single command using the runners shell
    - name: Tests
      run: yarn test
